checkTemplate: true
miniTitleLength: 8
labelToAdd:  'MISSING : INFORMATION :mag:'
issue:
  reactions:
    - confused
  badTitles:
    - update
    - updates
    - test
    - issue
    - debug
    - demo
  badTitleComment: >
    @{{ author }} Please provide us with more info about this issue title!

  badBodyComment: |
    @{{ author }} We would appreciate it if you could provide us with more info about this issue/pr!

    ![Alt Text](https://media.giphy.com/media/pqnY0eDsO7nvgHvjSv/giphy.gif)


pullRequest:
  reactions:
    - '-1'
  badTitles:
    - update
    - updates
    - pr
    - test
  badTitleComment: >
    @{{ author }} Please provide us with more info about this pr title!

  badBodyComment: |
    @{{ author }} We would appreciate it if you could provide us with more info about this issue/pr!

    ![Alt Text](https://media.giphy.com/media/pqnY0eDsO7nvgHvjSv/giphy.gif)
