checkTemplate: true
miniTitleLength: 8
labelToAdd: 'MISSING : INFORMATION :mag:'
issue:
  reactions:
    - eyes
  badTitles:
    - update
    - updates
    - test
    - issue
    - debug
    - demo
    - new
  badTitleComment: >
    @{{ author }} Please re-edit this issue title to provide more relevant info.

  badBodyComment: |
    @{{ author }} **Not enough information**. We would appreciate it if you could elaborate on your issue by filling the template!

pullRequest:
  reactions:
    - confused
    - '-1'
  badTitles:
    - update
    - updates
    - pr
    - test
    - new
  badTitleComment: >
    @{{ author }} Please provide us with more info about this pr title.

  badBodyComment: |
    @{{ author }} We would appreciate it if you could provide us with more info about this pr!

    ![Alt Text](https://media.giphy.com/media/pqnY0eDsO7nvgHvjSv/giphy.gif)
