name: Bug Report
description: File a bug report for VidGear
title: "[Bug]: "
labels: ["BUG :bug:", "NEED TRIAGE :police_car:"]
assignees:
  - abhiTronix
body:
  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the bug in 1-2 sentences, and why you consider it to be a bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Please describe precisely what you'd expect to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      description: Please describe precisely what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please describe the steps to reproduce the bug.
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant terminal log output. You can enable logging with `logging=True` in any Vidgear API for getting debug output. (Note: This will be automatically formatted into shell output, so no need for backticks)
      render: shell
  - type: input
    label: System/Environment information
    description: Please provide following details about the System/Environment you experienced the bug in:
    attributes:
      - label: VidGear Version
        description: What version of VidGear are you running? Run command `python -c "import vidgear; print(vidgear.__version__)"` to find out.
        placeholder: ex. 0.2.6
        validations:
          required: true
      - label: OpenCV version
        description: What version of OpenCV binaries you're running? Run command `python -c "import cv2; print(cv2.__version__)"` to find out.
        placeholder: ex. 4.6.0.66
        validations:
          required: true
      - label: Python version
        description: What version of Python you're running Vidgear on? Run command `python -V`  to find out.
        placeholder: ex. 3.7
        validations:
          required: true
      - label: Operating System and its version
        description: What Operating system you're using?
        placeholder: ex. Linux Mint 20.3 “Una” Xfce
        validations:
          required: true
  - type: textarea
    attributes:
      label: Any other Relevant Information?
      description: Provide any other relevant information(or screenshots) if available or else leave this block empty.
      placeholder: |-
        ex. Related Issue: xyz/foo#4083
    validations:
      required: false
