name: Bug Report
description: File a bug report for VidGear
title: "[Bug]: "
labels: ["BUG :bug:", "NEED TRIAGE :police_car:"]
assignees:
  - abhiTronix
body: 
  - 
    attributes: 
      description: "Please provide a brief description of the bug in 1-2 sentences, and why you consider it to be a bug"
      label: Description
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      options: 
        - 
          label: "I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful."
          required: true
        - 
          label: "I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related or helpful."
          required: true
        - 
          label: "I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree."
          required: true
    description: "By posting this issue you acknowledge the following"
    label: Acknowledgment
    type: checkboxes
  - 
    attributes: 
      description: "Please describe precisely what you'd expect to happen."
      label: "Expected behaviour"
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Please describe precisely what is actually happening."
      label: "Actual behaviour"
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Please describe the steps to reproduce the bug."
      label: "Steps to reproduce"
      placeholder: |-
          1. ...
          2. ...
          3. ...
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Please copy and paste any relevant terminal log output. You can enable logging with `logging=True` in any Vidgear API for getting debug output."
      label: "Relevant log output"
      render: shell
    type: textarea
  - 
    attributes: 
      - 
        description: "What version of VidGear are you running? Run command `python -c \"import vidgear; print(vidgear.__version__)\"` to find out."
        label: "VidGear Version"
        placeholder: "ex. 0.2.6"
        validations: 
          required: true
      - 
        description: "What version of OpenCV binaries you're running? Run command `python -c \"import cv2; print(cv2.__version__)\"` to find out."
        label: "OpenCV version"
        placeholder: "ex. 4.6.0.66"
        validations: 
          required: true
      - 
        description: "What version of Python you're running Vidgear on? Run command `python -V`  to find out."
        label: "Python version"
        placeholder: "ex. 3.7"
        validations: 
          required: true
      - 
        description: "What Operating system you're using?"
        label: "Operating System and its version"
        placeholder: "ex. Linux Mint 20.3 “Una” Xfce"
        validations: 
          required: true
    description: "Please provide following details about the System/Environment you experienced this bug"
    label: "System/Environment information"
    type: input
  - 
    attributes: 
      description: "Provide any other relevant information(or screenshots) if available or else leave this block empty."
      label: "Any other Relevant Information?"
      placeholder: "ex. Related Issue: xyz/foo#4083"
    type: textarea
    validations: 
      required: false
